### PR TITLE
Java 21 migration with Spring 3 and Terraform 

### PR DESCRIPTION
**Pull request by dgurjar-ch**
Updated java 21
updated Springboot 3.3
updated companies-house-parent 2.1.6
Create  and configured AWS terraform

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by foman-ch — APPROVED** [review]

**Review by vshastri-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Pull request merged**
